const ADD = "ADD";
const UPDATE_MOVIE_DATA = "UPDATE_MOVIE_DATA";
const UPDATE_TOGGLE_STATE = "UPDATE_TOGGLE_STATE";
const DELETE = "DELETE";
const FILTER = "FILTER";

export { ADD, UPDATE_MOVIE_DATA, UPDATE_TOGGLE_STATE, DELETE, FILTER };
